const CONFIG={spreadsheetId:"1vnIouZJf1iCYqDfFF6A4gDkfEk-hsSVEhLtPXcFDcB0",placesSheet:"Places",linksSheet:"CommunityLinks",homeLimit:10};
const COMMUNITY_META={"avery ridge":{brand:"Centex",city:"Gainesville"},"hunters creek":{brand:"Pulte",city:"Flowery Branch"},"reunion":{brand:"Pulte",city:"Flowery Branch"}};
const state={places:[],links:[]};const $=id=>document.getElementById(id);const text=(v,f="")=>String(v??f).trim();const norm=v=>text(v).normalize("NFKC").replace(/\s+/g," ").toLowerCase();
function csvUrl(sheet){return `https://docs.google.com/spreadsheets/d/${CONFIG.spreadsheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(sheet)}&_=${Date.now()}`}
function parseCSV(input){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<input.length;i++){const c=input[i],n=input[i+1];if(quoted&&c==='"'&&n==='"'){field+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(field);field=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(x=>x!==""))rows.push(row);row=[];field=""}else field+=c}row.push(field);if(row.some(x=>x!==""))rows.push(row);return rows}
function rowsToObjects(rows){if(!rows.length)return[];const h=rows[0].map(text);return rows.slice(1).map(r=>{const o={};h.forEach((k,i)=>{if(k)o[k]=text(r[i])});return o})}
async function fetchSheet(sheet){const r=await fetch(csvUrl(sheet),{cache:"no-store"});if(!r.ok)throw new Error(`Could not load ${sheet}`);const body=await r.text();if(/Sign in|Request access|<!doctype html/i.test(body.slice(0,700)))throw new Error(`${sheet} feed unavailable`);return rowsToObjects(parseCSV(body))}
function slugify(v){return text(v).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/&/g," and ").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function placeSlug(p){return `${slugify(p.Place)}-${slugify(p.City)}`}
function placeCategory(p){return text(p["Public Category (Auto)"],text(p.Category,"Other"))}
function placeNotes(p){return text(p["Client Notes"],text(p["Vibe / Good For"]))}
function uniqSorted(v){return [...new Set(v.filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function option(v){const o=document.createElement("option");o.value=v;o.textContent=v;return o}
function isActive(p){const s=norm(p["Place Status"]);return !s||s==="active"}
function linkedKeys(community){if(!community||norm(community)==="all")return null;const ids=new Set(),names=new Set();state.links.filter(l=>norm(l.Community)===norm(community)).forEach(l=>{if(text(l["Place ID"]))ids.add(norm(l["Place ID"]));if(text(l["Place (auto)"]))names.add(`${norm(l["Place (auto)"])}|${norm(l["City (auto)"])}`)});return{ids,names}}
function buildPlaceCard(p){const card=document.createElement("article");card.className="place-card";const name=text(p.Place,"Unnamed place"),city=text(p.City),area=text(p["Area / Neighborhood"]),cat=placeCategory(p),price=text(p.Price),summary=placeNotes(p),href=`/place.html?slug=${encodeURIComponent(placeSlug(p))}`;card.innerHTML=`<div class="card-top"><div class="meta"><span class="pill category"></span></div>${price?'<span class="price"></span>':''}</div><h3><a class="place-title-link"></a></h3><div class="place-location"></div>${summary?'<p class="notes"></p>':''}<div class="card-actions"><a class="primary-link"></a></div>`;card.querySelector(".pill.category").textContent=cat;card.querySelector(".place-title-link").textContent=name;card.querySelector(".place-title-link").href=href;if(price)card.querySelector(".price").textContent=price;const loc=card.querySelector(".place-location");loc.textContent=[city,area].filter(Boolean).join(" · ");loc.style.fontSize=".72rem";loc.style.color="#697080";loc.insertAdjacentText("afterbegin","⌾ ");if(summary)card.querySelector(".notes").textContent=summary;const a=card.querySelector(".primary-link");a.href=href;a.textContent="Explore this place";return card}
function filteredPlaces(){const q=norm($("searchInput")?.value),city=norm($("cityFilter")?.value||"All"),cat=norm($("categoryFilter")?.value||"All"),community=text($("placeCommunityFilter")?.value||"All"),linked=linkedKeys(community);return state.places.filter(isActive).filter(p=>{if(city!=="all"&&norm(p.City)!==city)return false;if(cat!=="all"&&norm(placeCategory(p))!==cat)return false;if(linked){const id=text(p["Place ID"]),nameKey=`${norm(p.Place)}|${norm(p.City)}`;if(!(id&&linked.ids.has(norm(id)))&&!linked.names.has(nameKey))return false}if(!q)return true;return norm([p.Place,p.City,p.Category,p["Public Category (Auto)"],p["Area / Neighborhood"],p["Tags / Best For"],p["Client Notes"]].join(" ")).includes(q)})}
function renderPlaces(){const grid=$("placesGrid");if(!grid)return;const results=filteredPlaces();grid.replaceChildren();results.slice(0,CONFIG.homeLimit).forEach(p=>grid.appendChild(buildPlaceCard(p)));if(!results.length){const d=document.createElement("div");d.className="empty-state";d.textContent="No places match those filters yet.";grid.appendChild(d)}if($("resultCount"))$("resultCount").textContent=`${results.length.toLocaleString()} place${results.length===1?"":"s"} to discover`;if($("showingCount"))$("showingCount").textContent=`Showing ${Math.min(results.length,CONFIG.homeLimit)} of ${results.length}`;const all=$("viewAllResults");if(all){const u=new URL("/search.html",location.origin),q=text($("searchInput")?.value),cityV=text($("cityFilter")?.value),catV=text($("categoryFilter")?.value);if(q)u.searchParams.set("q",q);if(cityV&&norm(cityV)!=="all")u.searchParams.set("city",cityV);if(catV&&norm(catV)!=="all")u.searchParams.set("category",catV);all.href=u.pathname+u.search}}
function renderCities(){const w=$("cityLinks");if(!w)return;w.replaceChildren();uniqSorted(state.places.filter(isActive).map(p=>text(p.City))).forEach(city=>{const a=document.createElement("a");a.href=`/cities/${slugify(city)}`;a.textContent=city;w.appendChild(a)})}
function renderCommunities(){const w=$("featuredCommunities");if(!w)return;w.replaceChildren();uniqSorted(state.links.map(l=>text(l.Community))).slice(0,3).forEach(community=>{const links=state.links.filter(l=>norm(l.Community)===norm(community)),unique=new Set(links.map(l=>text(l["Place ID"],`${text(l["Place (auto)"])}|${text(l["City (auto)"])}`)).filter(Boolean)),meta=COMMUNITY_META[norm(community)]||{},brand=text(links[0]?.Brand,text(links[0]?.Builder,meta.brand||"New homes")),city=text(links[0]?.["Community City"],text(links[0]?.City,meta.city||"")),href=`/communities/${slugify(community)}`;const c=document.createElement("article");c.className="featured-community-card";c.innerHTML=`<span class="builder-line"></span><span class="community-arrow">↗</span><span class="house-icon">⌂</span><h3></h3><p></p><a></a>`;c.querySelector(".builder-line").textContent=[brand,city].filter(Boolean).join(" · ");c.querySelector("h3").textContent=community;c.querySelector("p").textContent=`${unique.size} places to explore in the area`;const a=c.querySelector("a");a.href=href;a.textContent="Get to know the neighborhood";c.addEventListener("click",e=>{if(e.target.tagName!=="A")location.href=href});c.style.cursor="pointer";w.appendChild(c)})}
function populate(){const active=state.places.filter(isActive),cities=uniqSorted(active.map(p=>text(p.City))),cats=uniqSorted(active.map(placeCategory)),communities=uniqSorted(state.links.map(l=>text(l.Community)));cities.forEach(v=>$("cityFilter")?.appendChild(option(v)));cats.forEach(v=>$("categoryFilter")?.appendChild(option(v)));communities.forEach(v=>$("placeCommunityFilter")?.appendChild(option(v)));if($("placeCount"))$("placeCount").textContent=active.length;if($("cityCountNumber"))$("cityCountNumber").textContent=cities.length}
function bind(){["searchInput","cityFilter","categoryFilter","placeCommunityFilter"].forEach(id=>$(id)?.addEventListener(id==="searchInput"?"input":"change",renderPlaces))}
async function init(){bind();try{const[places,links]=await Promise.all([fetchSheet(CONFIG.placesSheet),fetchSheet(CONFIG.linksSheet)]);state.places=places.filter(p=>text(p.Place));state.links=links.filter(l=>text(l.Community)&&(text(l["Place ID"])||text(l["Place (auto)"])));populate();renderPlaces();renderCities();renderCommunities();if($("dataStatus"))$("dataStatus").textContent="Live guide connected"}catch(e){console.error(e);if($("resultCount"))$("resultCount").textContent="Could not load guide";if($("dataStatus"))$("dataStatus").textContent="Data feed unavailable";const g=$("placesGrid");if(g){const d=document.createElement("div");d.className="empty-state";d.textContent="The live directory could not load. Please refresh in a moment.";g.replaceChildren(d)}}}
document.addEventListener("DOMContentLoaded",init);