const CONFIG={spreadsheetId:"1vnIouZJf1iCYqDfFF6A4gDkfEk-hsSVEhLtPXcFDcB0",placesSheet:"Places"};
const $=id=>document.getElementById(id);const text=(v,f="")=>String(v??f).trim();const norm=v=>text(v).normalize("NFKC").replace(/\s+/g," ").toLowerCase();
function csvUrl(sheet){return `https://docs.google.com/spreadsheets/d/${CONFIG.spreadsheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(sheet)}&_=${Date.now()}`}
function parseCSV(s){const rows=[];let row=[],field="",q=false;for(let i=0;i<s.length;i++){const c=s[i],n=s[i+1];if(q&&c==='"'&&n==='"'){field+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(field);field=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(x=>x!==""))rows.push(row);row=[];field=""}else field+=c}row.push(field);if(row.some(x=>x!==""))rows.push(row);return rows}
function objects(rows){if(!rows.length)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]||"").trim()]))) }
async function fetchSheet(sheet){const r=await fetch(csvUrl(sheet),{cache:"no-store"});if(!r.ok)throw new Error(sheet);const body=await r.text();if(/Sign in|Request access|<!doctype html/i.test(body.slice(0,700)))throw new Error("feed unavailable");return objects(parseCSV(body))}
function slugify(v){return text(v).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/&/g," and ").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function placeSlug(p){return `${slugify(p.Place)}-${slugify(p.City)}`}
function paramSlug(){const p=new URLSearchParams(location.search);return p.get("slug")||p.get("id")||location.pathname.split("/").filter(Boolean).pop()||""}
function mapLink(address){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`}
function isActive(p){const s=norm(p["Place Status"]);return !s||s==="active"}
function addFact(label,value){if(!value||/^(unknown|not verified)$/i.test(value))return;const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=label;dd.textContent=value;$("factsGrid").append(dt,dd)}
function pill(v,cls=""){if(!v)return;const s=document.createElement("span");s.className=`pill ${cls}`.trim();s.textContent=v;$("placePills").appendChild(s)}
function action(label,href,primary=false){if(!href)return;const a=document.createElement("a");a.href=href;a.target="_blank";a.rel="noopener noreferrer";a.className=`button ${primary?"place-action-primary":"place-action-secondary"}`;a.textContent=label;$("placeActions").appendChild(a)}
function relatedCard(p){const a=document.createElement("a");a.className="related-place-card";a.href=`/places/${encodeURIComponent(placeSlug(p))}`;a.innerHTML=`<strong></strong><span></span><p></p>`;a.querySelector("strong").textContent=text(p.Place);a.querySelector("span").textContent=[text(p.City),text(p["Public Category (Auto)"],text(p.Category))].filter(Boolean).join(" · ");a.querySelector("p").textContent=text(p["Client Notes"],text(p["Vibe / Good For"]));return a}
function setMeta(p){const name=text(p.Place),city=text(p.City),category=text(p["Public Category (Auto)"],text(p.Category)),summary=text(p["Client Notes"],text(p["Vibe / Good For"]));const title=`${name} in ${city} | Atlanta Local by Logan`;const desc=[name,category&&`is a ${category.toLowerCase()} option`,city&&`in ${city}, Georgia`,summary].filter(Boolean).join(". ").slice(0,160);document.title=title;$("metaDescription").content=desc;$("ogTitle").content=title;$("ogDescription").content=desc;$("ogUrl").content=location.href;$("canonicalLink").href=`${location.origin}/places/${encodeURIComponent(placeSlug(p))}`}
function addSchema(p){const schema={"@context":"https://schema.org","@type":"Place",name:text(p.Place),description:text(p["Client Notes"],text(p["Vibe / Good For"])),address:text(p.Address)?{"@type":"PostalAddress","streetAddress":text(p.Address)}:undefined,url:text(p["Website / Source"])||undefined};Object.keys(schema).forEach(k=>schema[k]===undefined&&delete schema[k]);const s=document.createElement("script");s.type="application/ld+json";s.textContent=JSON.stringify(schema);document.head.appendChild(s)}
function render(p,places){setMeta(p);addSchema(p);const name=text(p.Place),category=text(p["Public Category (Auto)"],text(p.Category)),city=text(p.City),citySlug=slugify(city),area=text(p["Area / Neighborhood"]),price=text(p.Price);$("breadcrumbName").textContent=name;if($("breadcrumbCity")){$("breadcrumbCity").textContent=city;$("breadcrumbCity").href=`/cities/${citySlug}`;}$("placeName").textContent=name;pill(city);pill(category,"category");pill(price);$("placeSummary").textContent=[area,text(p["Vibe / Good For"])].filter(Boolean).join(" · ");$("aboutText").textContent=text(p["Client Notes"],text(p["Vibe / Good For"],`${name} is included in the guide as a local option in ${city}.`));addFact("Category",text(p.Category));addFact("Neighborhood",area);addFact("Hours",text(p["Hours / Schedule"]));addFact("Pricing",text(p["Pricing Details"]));addFact("Parking",text(p.Parking));addFact("Reservations",text(p["Reservations?"]));addFact("Patio",text(p["Patio?"]));addFact("Kid friendly",text(p["Kid Friendly?"]));addFact("Dog friendly",text(p["Dog Friendly?"]));addFact("Dress level",text(p["Dress Level"]));const addr=text(p.Address),web=text(p["Website / Source"]);action("Directions ↗",addr?mapLink(addr):"",true);action("Official website ↗",web,false);const visit=[];if(addr)visit.push(`<div><strong>Address</strong><span>${addr}</span></div>`);if(text(p["Hours / Schedule"]))visit.push(`<div><strong>Hours</strong><span>${text(p["Hours / Schedule"])}</span></div>`);if(text(p["Pricing Details"]))visit.push(`<div><strong>Pricing</strong><span>${text(p["Pricing Details"])}</span></div>`);$("visitDetails").innerHTML=visit.join("");const tags=text(p["Tags / Best For"]).split(",").map(x=>x.trim()).filter(Boolean);if(tags.length){$("tagsSection").hidden=false;tags.forEach(t=>{const s=document.createElement("span");s.className="pill category";s.textContent=t;$("tagList").appendChild(s)})}if($("cityContextHeading"))$("cityContextHeading").textContent=`Explore more of ${city}.`;if($("cityContextText"))$("cityContextText").textContent=`See more restaurants, activities, shopping and local favorites around ${city}, then use Moving Here for practical relocation context.`;if($("cityContextLink")){$("cityContextLink").href=`/cities/${citySlug}`;$("cityContextLink").textContent=`Explore ${city} →`;}const pid=text(p["Place ID"]);const related=places.filter(x=>isActive(x)&&text(x["Place ID"])!==pid&&norm(x.City)===norm(city)).slice(0,6);if(related.length){$("relatedSection").hidden=false;related.forEach(x=>$("relatedGrid").appendChild(relatedCard(x)))}$("placeLoading").hidden=true;$("placeContent").hidden=false}
async function init(){try{const places=await fetchSheet(CONFIG.placesSheet);const key=decodeURIComponent(paramSlug());const p=places.find(x=>text(x["Place ID"])===key||placeSlug(x)===key);if(!p)throw new Error("not found");render(p,places)}catch(e){console.error(e);$("placeLoading").hidden=true;$("placeError").hidden=false}}
document.addEventListener("DOMContentLoaded",init);