const CONFIG={spreadsheetId:"1vnIouZJf1iCYqDfFF6A4gDkfEk-hsSVEhLtPXcFDcB0",sheet:"Places",pageSize:30};
const state={places:[],visible:30};
const $=id=>document.getElementById(id);const text=(v,f="")=>(v||f).trim();
function csvUrl(){return `https://docs.google.com/spreadsheets/d/${CONFIG.spreadsheetId}/gviz/tq?tqx=out:csv&sheet=${CONFIG.sheet}&_=${Date.now()}`}
function parseCSV(s){const rows=[];let row=[],field="",q=false;for(let i=0;i<s.length;i++){const c=s[i],n=s[i+1];if(q&&c==='"'&&n==='"'){field+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(field);field=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(x=>x!==""))rows.push(row);row=[];field=""}else field+=c}row.push(field);if(row.some(x=>x!==""))rows.push(row);return rows}
function objects(rows){if(!rows.length)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]||"").trim()]))) }
function slugify(v){return text(v).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/&/g," and ").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function placeSlug(p){return `${slugify(p.Place)}-${slugify(p.City)}`}
function mapLink(address){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`}
function category(p){return text(p["Public Category (Auto)"],text(p.Category,"Other"))}
function notes(p){return text(p["Client Notes"],text(p["Vibe / Good For"]))}
function uniq(v){return [...new Set(v.filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function opt(v,label=v){const o=document.createElement("option");o.value=v;o.textContent=label;return o}
function card(p){const a=document.createElement("article");a.className="place-card";const city=text(p.City),cat=category(p),price=text(p.Price),summary=notes(p),address=text(p.Address),website=text(p["Website / Source"]);a.innerHTML=`<div class="card-top"><h3><a class="place-title-link"></a></h3>${price?'<span class="price"></span>':''}</div><div class="meta"></div>${summary?'<p class="notes"></p>':''}<div class="card-actions"></div>`;const title=a.querySelector(".place-title-link");title.textContent=text(p.Place);title.href=`/place.html?slug=${encodeURIComponent(placeSlug(p))}`;if(price)a.querySelector(".price").textContent=price;const meta=a.querySelector(".meta");[city,cat].forEach((v,i)=>{if(!v)return;const s=document.createElement("span");s.className=`pill ${i?'category':''}`.trim();s.textContent=v;meta.appendChild(s)});if(summary)a.querySelector(".notes").textContent=summary;const actions=a.querySelector(".card-actions");const details=document.createElement("a");details.href=title.href;details.textContent="View details";details.className="primary-link";actions.appendChild(details);if(address){const m=document.createElement("a");m.href=mapLink(address);m.target="_blank";m.rel="noopener noreferrer";m.textContent="Map ↗";actions.appendChild(m)}if(website){const w=document.createElement("a");w.href=website;w.target="_blank";w.rel="noopener noreferrer";w.textContent="Website ↗";actions.appendChild(w)}return a}
function filtered(){const q=$("searchInput").value.trim().toLowerCase(),city=$("cityFilter").value,cat=$("categoryFilter").value,sort=$("sortFilter").value;let r=state.places.filter(p=>text(p["Place Status"])!=="Inactive").filter(p=>city==="All"||text(p.City)===city).filter(p=>cat==="All"||category(p)===cat).filter(p=>!q||[p.Place,p.City,p.Category,p["Public Category (Auto)"],p["Area / Neighborhood"],p["Tags / Best For"],p["Client Notes"],p.Address].join(" ").toLowerCase().includes(q));r.sort((a,b)=>sort==="city"?(text(a.City).localeCompare(text(b.City))||text(a.Place).localeCompare(text(b.Place))):text(a.Place).localeCompare(text(b.Place)));return r}
function syncUrl(){const u=new URL(location.href),pairs={q:$("searchInput").value.trim(),city:$("cityFilter").value,category:$("categoryFilter").value};Object.entries(pairs).forEach(([k,v])=>{if(v&&v!=="All")u.searchParams.set(k,v);else u.searchParams.delete(k)});history.replaceState(null,"",u)}
function render(reset=false){if(reset)state.visible=CONFIG.pageSize;const r=filtered(),grid=$("placesGrid");grid.replaceChildren();r.slice(0,state.visible).forEach(p=>grid.appendChild(card(p)));$("resultCount").textContent=`${r.length.toLocaleString()} place${r.length===1?"":"s"}`;$("loadMore").hidden=state.visible>=r.length;if(!r.length){const d=document.createElement("div");d.className="empty-state";d.textContent="No places match those filters yet.";grid.appendChild(d)}syncUrl()}
function seedFilters(){uniq(state.places.map(p=>text(p.City))).forEach(v=>$("cityFilter").appendChild(opt(v)));uniq(state.places.map(category)).forEach(v=>$("categoryFilter").appendChild(opt(v)));const u=new URL(location.href);$("searchInput").value=u.searchParams.get("q")||"";const city=u.searchParams.get("city"),cat=u.searchParams.get("category");if(city)[...$("cityFilter").options].some(o=>o.value===city)&&($("cityFilter").value=city);if(cat)[...$("categoryFilter").options].some(o=>o.value===cat)&&($("categoryFilter").value=cat)}
function bind(){["searchInput","cityFilter","categoryFilter","sortFilter"].forEach(id=>$(id).addEventListener(id==="searchInput"?"input":"change",()=>render(true)));$("clearFilters").addEventListener("click",()=>{$("searchInput").value="";$("cityFilter").value="All";$("categoryFilter").value="All";$("sortFilter").value="name";render(true)});$("loadMore").addEventListener("click",()=>{state.visible+=CONFIG.pageSize;render()})}
async function init(){bind();try{const r=await fetch(csvUrl(),{cache:"no-store"});if(!r.ok)throw new Error();state.places=objects(parseCSV(await r.text())).filter(p=>text(p.Place));seedFilters();render(true);$("dataStatus").textContent="Live data connected"}catch(e){console.error(e);$("dataStatus").textContent="Data feed unavailable";$("resultCount").textContent="Could not load guide"}}
document.addEventListener("DOMContentLoaded",init);